name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  get_storage: ^2.1.1
  permission_handler: ^11.3.1
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0
#  firebase_messaging: ^15.2.4
#  flutter_local_notifications: ^19.0.0



  #storage
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.8
#  firebase_auth: ^5.5.1
  firebase_core: ^2.5.1

  #local_authen
  local_auth: ^2.1.6
  url_launcher: ^6.1.11

  #Note_pen
  flutter_drawing_board: ^0.9.8

#  google_mobile_ads: ^2.0.0

  #Record
  record: ^6.0.0
  just_audio: ^0.10.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_quill: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  #storage
flutter:
  assets:
    - assets/images/
    - assets/vectors/
  uses-material-design: true
